{
 "title": "itmo-453 (Graphite B)",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Alias by Disk used (df root_percent bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productionb.hosts.*.df-root.percent_bytes-used"
    }
   ]
  },
  {
   "title": "Carbon Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(productionb.hosts.graphiteb.processes-carbon-relay.ps_count.processes, 2)"
    }
   ]
  },
  {
   "title": "Alias by Memory (used) all hosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productionb.hosts.*.memory.memory-used"
    }
   ]
  },
  {
   "title": "Riemann B Streams Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(productionb.hosts.riemannb.riemann.streams.latency.*, 6)"
    }
   ]
  },
  {
   "title": "Group by CPU (user and system) for all hosts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNode(productionb.hosts.*.cpu.{percent-user,percent-system},2,'sumSeries')"
    }
   ]
  },
  {
   "title": "Collectd Process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "productionb.hosts.*.processes-collectd.ps_count.processes"
    }
   ]
  }
 ]
}